##### VSCODE / REST Client https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# Create a .env file and set the corresponding variables
# See all $dotenv fields below

@endpoint=https://pretix.eu/api/v1/
@token={{$dotenv PRETIX_TOKEN}}


#########################
# organizers/
#########################

### 
GET {{endpoint}}/organizers/
Host: pretix.eu
Authorization: Token {{token}}

#########################
# events
#########################

GET {{endpoint}}/organizers/noi-digital/events
Host: pretix.eu
Authorization: Token {{token}}

#########################
# checkin list
#########################

GET {{endpoint}}/organizers/noi-digital/events/sfscon23/checkinlists
Host: pretix.eu
Authorization: Token {{token}}

#########################
# checkin list status
#########################

GET {{endpoint}}/organizers/noi-digital/events/sfscon23/checkinlists/313919/status
Host: pretix.eu
Authorization: Token {{token}}

#########################
# create conf checkin list status
#########################

@api=http://localhost:8000

GET {{api}}/openapi.json
Content-Type: application/json

#########################
# create conf checkin list status
#########################

POST {{api}}/api/conferences
Content-Type: application/json

{
    "default": "True",
    "force": "True"
}

#########################
# get conferences
#########################

GET {{api}}/api/conferences
Content-Type: application/json
